-- CreateEnum
CREATE TYPE "Sex" AS ENUM ('MALE', 'FEMALE', 'OTHER');

-- CreateEnum
CREATE TYPE "Exams" AS ENUM ('TRATAMENTO_POR_ALTA_POTENCIA_FLUORETOS_NA_MUCOSA_ORAL', 'MOLDAGEM_DENTAL_MAXILAR_PARA_CONSTRUCAO_DE_PROTESE_DENTA', 'REMBASAMENTO_E_CONSERTO_DE_PROTESE_DENTARIA', 'SESSAO_DE_IMPOSICAO_DE_MAOS', 'EXCISAO_E_SUTURA_DE_LESAO_NA_BOCA', 'ORIENTACAO_DE_HIGIENE_BUCAL', 'ORIENTACAO_DE_HIGIENIZACAO_DE_PROTESES_DENTARIAS', 'BIOPSIA_DOS_TECIDOS_MOLES_DA_BOCA', 'RADIOGRAFIA_PANORAMICA', 'RADIOGRAFIA_INTERPROXIMAL_BITE_WING', 'RADIOGRAFIA_PERIAPICAL', 'RESTAURACAO_DE_DENTE_PERMANENTE_ANTERIOR_COM_RESINA_COMPOSTA', 'RESTAURACAO_DE_DENTE_DECIDUO_POSTERIOR_COM_RESINA_COMPOSTA', 'RESTAURACAO_DE_DENTE_DECIDUO_ANTERIOR_COM_RESINA_COMPOSTA', 'RESTAURACAO_DE_DENTE_PERMANENTE_POSTERIOR_COM_RESINA_COMPOSTA', 'ADEQUACAO_DO_COMPORTAMENTO_DE_CRIANCAS', 'PROTESE_PARCIAL_MANDIBULAR_REMOVIVEL', 'PROTESE_PARCIAL_MAXILAR_REMOVIVEL', 'PROTESE_TOTAL_MANDIBULAR', 'PROTESE_TOTAL_MAXILAR');

-- CreateTable
CREATE TABLE "Patient" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "cpf" TEXT NOT NULL,
    "dateOfBirth" TIMESTAMP(3) NOT NULL,
    "sex" "Sex" NOT NULL,

    CONSTRAINT "Patient_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "HealthProfessional" (
    "id" SERIAL NOT NULL,
    "cro" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "position" TEXT NOT NULL,
    "sex" "Sex" NOT NULL,
    "dateOfBirth" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "HealthProfessional_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MedicalRecord" (
    "id" SERIAL NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "patientId" INTEGER NOT NULL,
    "doctorId" INTEGER NOT NULL,
    "anamnesis" TEXT NOT NULL,
    "clinicExam" "Exams"[],

    CONSTRAINT "MedicalRecord_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Patient_email_key" ON "Patient"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Patient_cpf_key" ON "Patient"("cpf");

-- CreateIndex
CREATE UNIQUE INDEX "HealthProfessional_cro_key" ON "HealthProfessional"("cro");

-- CreateIndex
CREATE UNIQUE INDEX "HealthProfessional_email_key" ON "HealthProfessional"("email");

-- AddForeignKey
ALTER TABLE "MedicalRecord" ADD CONSTRAINT "MedicalRecord_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicalRecord" ADD CONSTRAINT "MedicalRecord_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "HealthProfessional"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
